# Generated by Django 5.2.7 on 2025-11-19 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("presentation", "Presentation / PPT"),
                            ("logo", "Logo Design"),
                            ("web_scraping", "Web Scraping"),
                            ("poster", "Poster Design"),
                            ("word_to_excel", "Word to Excel"),
                            ("pdf_to_excel", "PDF to Excel"),
                            ("handwriting", "Handwriting to Word/Excel"),
                            ("data_entry", "Data Entry"),
                            ("teaching_material", "Teaching Material Creation"),
                            ("other", "Other Work"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "file_upload",
                    models.FileField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
