# Generated by Django 5.2.7 on 2025-11-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Required if callback is requested",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="request_call",
            field=models.BooleanField(default=False, verbose_name="Request a Callback"),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="description",
            field=models.TextField(
                help_text="Describe your project in detail (e.g., 600 pages book to PPT)."
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("presentation", "Presentation / PPT Creation"),
                    ("book_typing", "Book Typing / Structured Data"),
                    ("consultation", "One-to-One Consultation Call"),
                    ("web_scraping", "Web Scraping"),
                    ("data_entry", "Data Entry"),
                    ("other", "Other Custom Requirement"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("contacted", "Client Contacted"),
                    ("in_progress", "Work in Progress"),
                    ("completed", "Delivered"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
