# Generated by Django 5.2.7 on 2025-11-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="profile_pics/"
            ),
        ),
    ]
