# Generated by Django 5.2.7 on 2025-11-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_profile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="payment_screenshot",
            field=models.ImageField(blank=True, null=True, upload_to="payments/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
