# Generated by Django 5.2.7 on 2025-11-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_profile_is_paid_profile_payment_screenshot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "about_title",
                    models.CharField(default="About Hewor", max_length=200),
                ),
                (
                    "about_description",
                    models.TextField(help_text="Write your company story here."),
                ),
                (
                    "about_image",
                    models.ImageField(blank=True, null=True, upload_to="site/"),
                ),
                (
                    "contact_email",
                    models.EmailField(default="support@hewor.com", max_length=254),
                ),
                (
                    "contact_phone",
                    models.CharField(default="+91 879745xxxx", max_length=13),
                ),
                (
                    "contact_address",
                    models.TextField(default="Tech Park, New Delhi, India"),
                ),
            ],
        ),
    ]
