# Generated by Django 5.2.8 on 2025-11-21 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_profile_phone_number_delete_orderchat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_paid",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="payment_screenshot",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="transaction_id",
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="payment_screenshot",
            field=models.ImageField(blank=True, null=True, upload_to="payments/"),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(default="0000000000", max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="description",
            field=models.TextField(help_text="Describe your project in detail."),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name="OrderChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to="core.serviceorder",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
