# Generated by Django 5.2.7 on 2026-01-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_profile_is_paid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesetting",
            name="contact_phone",
            field=models.CharField(default="+91 8797456730", max_length=20),
        ),
    ]
