# Generated by Django 5.2.7 on 2026-01-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_sitesetting_contact_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="delivery_file",
            field=models.FileField(
                blank=True,
                help_text="Upload the final project file here.",
                null=True,
                upload_to="deliveries/",
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="delivery_message",
            field=models.TextField(
                blank=True, help_text="Message to the client upon delivery.", null=True
            ),
        ),
    ]
