# Generated by Django 5.2.7 on 2026-01-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_profile_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "position",
                    models.CharField(
                        help_text="Job Title (e.g., Head of Customer Experience)",
                        max_length=100,
                    ),
                ),
                ("review_text", models.TextField()),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="reviews/"),
                ),
                (
                    "rating",
                    models.IntegerField(default=5, help_text="Rating from 1 to 5"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
