# Generated by Django 5.2.7 on 2026-01-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgencyStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(help_text="e.g., 34+", max_length=50)),
                (
                    "label",
                    models.CharField(
                        help_text="e.g., Projects Delivered", max_length=100
                    ),
                ),
                (
                    "icon_color",
                    models.CharField(
                        choices=[
                            ("primary", "Blue"),
                            ("secondary", "Grey"),
                            ("accent", "Teal"),
                            ("success", "Green"),
                            ("danger", "Red"),
                            ("warning", "Yellow"),
                            ("info", "Cyan"),
                        ],
                        default="primary",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., PhD Thesis Acceptance", max_length=200
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="e.g., Thesis Formatting", max_length=100
                    ),
                ),
                (
                    "category_color",
                    models.CharField(
                        choices=[
                            ("primary", "Blue (Thesis)"),
                            ("danger", "Red (PPT)"),
                            ("info", "Cyan (Data)"),
                            ("success", "Green"),
                            ("warning", "Yellow"),
                            ("secondary", "Grey (Book)"),
                        ],
                        default="primary",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Success Story Image", upload_to="case_studies/"
                    ),
                ),
                (
                    "challenge",
                    models.TextField(help_text="Describe the challenge faced."),
                ),
                (
                    "solution",
                    models.TextField(help_text="Describe the solution provided."),
                ),
                (
                    "stat1_value",
                    models.CharField(help_text="e.g., 100%", max_length=50),
                ),
                (
                    "stat1_label",
                    models.CharField(help_text="e.g., Compliance", max_length=50),
                ),
                (
                    "stat2_value",
                    models.CharField(help_text="e.g., 48 Hrs", max_length=50),
                ),
                (
                    "stat2_label",
                    models.CharField(help_text="e.g., Turnaround", max_length=50),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display Order (lowest first)"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="case_studies_description",
            field=models.TextField(
                default="Discover how we help academicians and professionals stand out.",
                help_text="Short lead text under the title.",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="case_studies_subtitle",
            field=models.CharField(
                default="Real results for real clients.", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="case_studies_title",
            field=models.CharField(default="Client Success Stories", max_length=200),
        ),
    ]
