# Generated by Django 5.2.7 on 2026-01-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_agencystat_casestudy_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(help_text="e.g., FOUNDER & CEO", max_length=100),
                ),
                ("quote", models.TextField(help_text="Short quote or bio.")),
                ("image", models.ImageField(blank=True, null=True, upload_to="team/")),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                (
                    "twitter_url",
                    models.URLField(blank=True, help_text="X / Twitter URL", null=True),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display Order"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="about_leadership_subtitle",
            field=models.CharField(default="The minds behind Hewor.", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="about_leadership_title",
            field=models.CharField(default="Meet Our Leadership", max_length=200),
        ),
    ]
