# Generated by Django 5.2.7 on 2026-01-23 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_teammember_sitesetting_about_leadership_subtitle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="order_files/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="core.serviceorder",
                    ),
                ),
            ],
        ),
    ]
