# Generated by Django 5.2.7 on 2026-01-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_orderfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("source", "Source File (User)"),
                    ("delivery", "Delivery File (Admin)"),
                ],
                default="source",
                max_length=20,
            ),
        ),
    ]
