# Generated by Django 5.2.7 on 2026-01-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_orderfile_file_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderfile",
            name="original_filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
