# Generated by Django 5.2.7 on 2026-01-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_orderfile_original_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="freelancer",
            field=models.CharField(
                blank=True,
                help_text="Assigned freelancer name",
                max_length=100,
                null=True,
            ),
        ),
    ]
