# Generated by Django 5.2.7 on 2026-01-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_serviceorder_freelancer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Freelancer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "freelancer_id",
                    models.CharField(
                        help_text="Unique ID for the freelancer",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="freelancers/"),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "profession",
                    models.CharField(
                        help_text="e.g. Web Developer, Content Writer", max_length=100
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "expertise",
                    models.TextField(help_text="List of skills or expertise areas"),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
