# Generated by Django 5.2.7 on 2026-01-23 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_freelancer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="freelancer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="freelancer_description",
            field=models.TextField(
                blank=True,
                help_text="Detailed work description for freelancer",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="freelancer_roadmap",
            field=models.FileField(
                blank=True,
                help_text="Upload roadmap/instructions for freelancer",
                null=True,
                upload_to="roadmaps/",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="freelancer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_orders",
                to="core.freelancer",
            ),
        ),
        migrations.CreateModel(
            name="FreelancerChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="chat_attachments/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freelancer_chats",
                        to="core.serviceorder",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
