# Generated by Django 5.2.7 on 2026-01-23 21:19

from django.db import migrations
from django.contrib.auth import get_user_model

def reset_order_admin_password(apps, schema_editor):
    User = get_user_model()
    username = "Hewor.order"
    password = "Hewor.order@a2025M"
    email = "order_admin@hewor.in"
    
    # We use filter().first() to avoid errors if the user model schema has changed significantly
    # ensuring we get the user if they exist
    users = User.objects.filter(username=username)
    if users.exists():
        user = users.first()
        print(f"Updating password for existing user: {username}")
    else:
        print(f"Creating user: {username}")
        user = User.objects.create_user(username=username, email=email)
        
    user.set_password(password)
    user.save()

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_freelancer_user_serviceorder_freelancer_description_and_more"),
    ]

    operations = [
        migrations.RunPython(reset_order_admin_password),
    ]
