# Generated by Django 5.2.7 on 2026-01-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_fix_order_admin_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="freelancer",
            name="payment_details",
            field=models.TextField(
                blank=True, help_text="Bank details or UPI ID", null=True
            ),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="qr_code",
            field=models.ImageField(
                blank=True,
                help_text="Upload QR Code for payments",
                null=True,
                upload_to="freelancer_qr/",
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="freelancer_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for the freelancer to complete the work",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="freelancer_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending_acceptance", "Pending Acceptance"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("timeout", "Timeout (No Response)"),
                ],
                default="pending_acceptance",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="is_freelancer_paid",
            field=models.BooleanField(default=False),
        ),
    ]
