# Generated by Django 5.2.7 on 2026-01-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_freelancer_payment_details_freelancer_qr_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="freelancer_payment_screenshot",
            field=models.ImageField(
                blank=True, null=True, upload_to="freelancer_payments/"
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="freelancer_transaction_id",
            field=models.CharField(
                blank=True,
                help_text="Transaction ID for payment to freelancer",
                max_length=100,
                null=True,
            ),
        ),
    ]
