# Generated by Django 5.2.7 on 2026-01-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_serviceorder_freelancer_payment_screenshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="freelancer_payment",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Payment amount for freelancer (₹)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
