# Generated by Django 5.2.7 on 2026-01-26 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_freelancernotification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Short summary for listings and SEO", max_length=300
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="HTML content of the blog post"),
                ),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="blog/"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pdf-tips", "PDF Tips & Tricks"),
                            ("tutorials", "Tutorials"),
                            ("productivity", "Productivity"),
                            ("tools", "Tool Guides"),
                            ("news", "News & Updates"),
                        ],
                        default="pdf-tips",
                        max_length=50,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=200
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                (
                    "is_ai_generated",
                    models.BooleanField(
                        default=False, help_text="Content was AI-assisted"
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
