from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup_view, name='signup'),
    path('verify-otp/', views.verify_otp, name='verify_otp'), # New URL
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('create-order/', views.create_order, name='create_order'),
    path('profile/', views.profile_view, name='profile'),
    path('payment/<int:order_id>/', views.payment_view, name='payment'),
    path('about/', views.about_view, name='about'),
    path('services/', views.services_view, name='services'),
    path('faqs/', views.faqs_view, name='faqs'),
    path('case-studies/', views.case_studies_view, name='case_studies'),
    path('terms/', views.terms_view, name='terms'),
    path('privacy/', views.privacy, name='privacy'),
    path('contact/', views.contact_view, name='contact'),
    path('order/<int:order_id>/', views.order_detail, name='order_detail'),
    path('api/chatbot/', views.chatbot_api, name='chatbot_api'),
    path('order/<int:order_id>/download/<str:file_type>/', views.download_order_files, name='download_order_files'),
    path('order-panel/login/', views.order_panel_login, name='order_panel_login'),
    path('order-panel/', views.order_panel_dashboard, name='order_panel_dashboard'),
    path('order-panel/upload/<int:order_id>/', views.order_panel_upload, name='order_panel_upload'),
    path('order-panel/mark-delivered/<int:order_id>/', views.order_panel_mark_delivered, name='order_panel_mark_delivered'),
    path('order-panel/assign-freelancer/<int:order_id>/', views.order_panel_assign_freelancer, name='order_panel_assign_freelancer'),
    path('order-panel/freelancers/', views.order_panel_freelancers, name='order_panel_freelancers'),
    path('order-panel/manage-works/', views.manage_freelancer_works, name='manage_freelancer_works'),
    path('order-panel/pay-freelancer/<int:order_id>/', views.order_panel_pay_freelancer, name='order_panel_pay_freelancer'),
    path('order-panel/freelancers/delete/<int:freelancer_id>/', views.order_panel_delete_freelancer, name='order_panel_delete_freelancer'),
    path('order-panel/freelancer/<int:freelancer_id>/', views.order_panel_freelancer_detail, name='order_panel_freelancer_detail'),
    path('order-panel/chat/<int:order_id>/', views.order_panel_freelancer_chat, name='order_panel_freelancer_chat'),
    
    # Freelancer Portal
    path('freelancer/login/', views.freelancer_login, name='freelancer_login'),
    path('freelancer/dashboard/', views.freelancer_dashboard, name='freelancer_dashboard'),
    path('freelancer/project/<int:order_id>/', views.freelancer_order_detail, name='freelancer_order_detail'),
    path('freelancer/order/<int:order_id>/accept/', views.freelancer_accept_order, name='freelancer_accept_order'),
    path('freelancer/order/<int:order_id>/reject/', views.freelancer_reject_order, name='freelancer_reject_order'),

    # Free Tools
    path('tools/', views.tools_list, name='tools_list'),
    path('tools/merge-pdf/', views.merge_pdf_tool, name='merge_pdf_tool'),
    path('tools/split-pdf/', views.split_pdf_tool, name='split_pdf_tool'),
    path('tools/compress-pdf/', views.compress_pdf_tool, name='compress_pdf_tool'),
    path('tools/pdf-to-word/', views.pdf_to_word_tool, name='pdf_to_word_tool'),
    path('tools/pdf-to-powerpoint/', views.pdf_to_ppt_tool, name='pdf_to_ppt_tool'),
    path('tools/pdf-to-excel/', views.pdf_to_excel_tool, name='pdf_to_excel_tool'),
    path('tools/word-to-pdf/', views.word_to_pdf_tool, name='word_to_pdf_tool'),
    path('tools/excel-to-pdf/', views.excel_to_pdf_tool, name='excel_to_pdf_tool'),
    path('tools/ppt-to-pdf/', views.ppt_to_pdf_tool, name='ppt_to_pdf_tool'),
    path('tools/pdf-to-jpg/', views.pdf_to_jpg_tool, name='pdf_to_jpg_tool'),
    path('tools/jpg-to-pdf/', views.jpg_to_pdf_tool, name='jpg_to_pdf_tool'),
    path('tools/sign-pdf/', views.sign_pdf_tool, name='sign_pdf_tool'),
    path('tools/html-to-pdf/', views.html_to_pdf_tool, name='html_to_pdf_tool'),
    path('tools/rotate-pdf/', views.rotate_pdf_tool, name='rotate_pdf_tool'),
    path('tools/add-watermark/', views.add_watermark_tool, name='add_watermark_tool'),
    path('tools/protect-pdf/', views.protect_pdf_tool, name='protect_pdf_tool'),
    path('tools/unlock-pdf/', views.unlock_pdf_tool, name='unlock_pdf_tool'),
    path('tools/add-page-numbers/', views.add_page_numbers_tool, name='add_page_numbers_tool'),
    path('tools/remove-pages/', views.remove_pages_tool, name='remove_pages_tool'),
    path('tools/extract-pages/', views.extract_pages_tool, name='extract_pages_tool'),
    path('tools/whiteboard/', views.whiteboard_tool, name='whiteboard_tool'),
]


