"""
Django settings for hewor_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



from dotenv import load_dotenv
import os

load_dotenv()

# --- FIREBASE SETUP ---
import firebase_admin
from firebase_admin import credentials

import json

FIREBASE_CREDENTIALS_PATH = os.path.join(BASE_DIR, 'firebase-adminsdk.json')
FIREBASE_ADMIN_CREDENTIALS_ENV = os.environ.get('FIREBASE_ADMIN_CREDENTIALS')

if not firebase_admin._apps:
    if FIREBASE_ADMIN_CREDENTIALS_ENV:
        # Load from Environment Variable (Best for Heroku/Render)
        try:
            cred_dict = json.loads(FIREBASE_ADMIN_CREDENTIALS_ENV)
            cred = credentials.Certificate(cred_dict)
            firebase_admin.initialize_app(cred)
        except Exception as e:
            print(f"ERROR: Failed to initialize Firebase from environment variable: {e}")
    elif os.path.exists(FIREBASE_CREDENTIALS_PATH):
        # Load from File (Best for Local Dev)
        try:
            cred = credentials.Certificate(FIREBASE_CREDENTIALS_PATH)
            firebase_admin.initialize_app(cred)
        except Exception as e:
             print(f"ERROR: Failed to initialize Firebase from file: {e}")
    else:
        print(f"WARNING: Firebase credentials not found. Google Auth will fail.")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-default-key-changeme')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['*'] # Default fallback
if not DEBUG:
    ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '.railway.app,hewor.in').split(',')

CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://127.0.0.1,http://localhost').split(',')
CSRF_TRUSTED_ORIGINS.extend(['https://hewor.in', 'https://www.hewor.in'])

# ... (omitted app config) ...

# Remove debug prints for production security



# Application definition

INSTALLED_APPS = [
    'jazzmin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'core',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Enabled for production static files
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "hewor_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "hewor_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url
import os

if os.environ.get('DATABASE_URL') or os.environ.get('MYSQLHOST') or os.environ.get('DB_HOST'):
    # Production (Railway) - Use MySQL
    try:
        DATABASES = {
            'default': dj_database_url.config(
                default=f"mysql://{os.environ.get('MYSQLUSER', os.environ.get('DB_USER', 'root'))}:{os.environ.get('MYSQLPASSWORD', os.environ.get('DB_PASSWORD', ''))}@{os.environ.get('MYSQLHOST', os.environ.get('DB_HOST', '127.0.0.1'))}:{os.environ.get('MYSQLPORT', os.environ.get('DB_PORT', '3306'))}/{os.environ.get('MYSQLDATABASE', os.environ.get('DB_NAME', 'hewor_db'))}",
                conn_max_age=600,
            )
        }
        print("DEBUG: Production Database Configuration Loaded Successfully.")
    except Exception as e:
        print(f"CRITICAL ERROR: Failed to configure Production Database: {e}")
        print("Falling back to SQLite to ensure site boots.")
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
else:
    # Local Development - Use SQLite
    print("Using Local SQLite Database")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = str(BASE_DIR / "staticfiles")
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# ... (omitted)

JAZZMIN_UI_TWEAKS = {
    "theme": "solar",
    "navbar": "navbar-dark",
    "theme_body": "dark",
}


# MEDIA settings were already defined above.
# Logging config follows.

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}